# Copyright (c) 2026 APSOS — App and Software Solutions Wörner. All rights reserved.

[application]
name             = "chord_shifter"
default_platform = "web"

[web.app]
title = "Chord Shifter"

[web.watcher]
watch_path = ["src"]
reload_html = true
